version: '3.8'

services:
  php:
    build: .
    container_name: symfony_e-store-php
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      database:
        condition: service_healthy
    environment:
      PGPASSWORD: symfony

  nginx:
    image: nginx:alpine
    container_name: symfony_e-store-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  database:
    image: postgres:16-alpine
    container_name: symfony_e-store-database
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  mailer:
    image: axllent/mailpit
    container_name: symfony_e-store-mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8025"]
      interval: 5s
      timeout: 5s
      retries: 3
