auth_controllers:
    resource:
        path: ../src/Auth/Controller/
        namespace: App\Auth\Controller
    type: attribute

shop_controllers:
    resource:
        path: ../src/Shop/Controller/
        namespace: App\Shop\Controller
    type: attribute

core_controllers:
    resource:
        path: ../src/Core/Controller/
        namespace: App\Core\Controller
    type: attribute

product_controllers:
    resource: 
        path: '../src/Product/Controller/'
        namespace: App\Product\Controller
    type: attribute

cart_controllers:
    resource: 
        path: '../src/Cart/Controller/'
        namespace: App\Cart\Controller
    type: attribute

admin_controllers:
    resource:
        path: '../src/Admin/Controller/'
        namespace: App\Admin\Controller
    type: attribute

wishlist_controllers:
    resource: 
        path: '../src/Wishlist/Controller/'
        namespace: App\Wishlist\Controller
    type: attribute